#@ load("/values.star", "values")
#@ load("/globals.star", "globals")
#@ load("/helpers.star", "generate_gangway_tls")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("certificates.lib.yaml", "generate_dns_names", "generate_self_signed_issuer", "generate_ca_issuer", "generate_ca_certificate", "generate_certificate")

#@ if values.gangway.ingress.enabled:
#@ gangway_name = "gangway"
#@ gangway_namespace = values.gangway.namespace
#@ gangway_organization = "Project Gangway"
#@ gangway_self_signed_ca_issuer = gangway_name + "-self-signed-ca-issuer"
#@ gangway_ca = gangway_name + "-ca"
#@ gangway_ca_common_name = "Gangway CA"
#@ gangway_ca_dns_name = gangway_name + "ca"
#@ gangway_ca_key_pair = gangway_name + "-ca-key-pair"
#@ gangway_ca_issuer = gangway_name + "-ca-issuer"
#@ gangway_cert = gangway_name + "-cert"
#@ gangway_cert_duration = "87600h"
#@ gangway_cert_renew_before = "360h"

--- #@ generate_self_signed_issuer(gangway_self_signed_ca_issuer, gangway_namespace)
--- #@ generate_ca_certificate(gangway_ca, gangway_namespace, gangway_cert_duration, gangway_cert_renew_before, gangway_ca_key_pair, [gangway_organization], gangway_ca_common_name, [gangway_ca_dns_name], gangway_self_signed_ca_issuer)
--- #@ generate_ca_issuer(gangway_ca_issuer, gangway_namespace, gangway_ca_key_pair)

#@ gangway_tls_cert = "gangway-tls-cert"
#@ gangway_tls_secret = "gangway-tls"
#@ gangway_tls_common_name = "gangway"
#@ if generate_gangway_tls():
--- #@ generate_certificate(gangway_tls_cert, gangway_namespace, gangway_cert_duration, gangway_cert_renew_before, gangway_tls_secret, [gangway_organization], gangway_tls_common_name, [values.gangway.ingress.virtual_host_fqdn, "notary." + values.gangway.ingress.virtual_host_fqdn], gangway_ca_issuer)
#@ end

#@ if not generate_gangway_tls():
#@ ca_crt = getattr(values.gangway.ingress.tlsCertificate, "ca.crt")
#@ tls_crt = getattr(values.gangway.ingress.tlsCertificate, "tls.crt")
#@ tls_key = getattr(values.gangway.ingress.tlsCertificate, "tls.key")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ gangway_tls_secret
  namespace: #@ gangway_namespace
type: kubernetes.io/tls
data:
  #@ if/end ca_crt:
  ca.crt: #@ base64.encode(ca_crt)
  tls.crt: #@ base64.encode(tls_crt)
  tls.key: #@ base64.encode(tls_key)
#@ end

#@ end
