#@ load("/values.star", "values")
#@ load("/globals.star", "globals")
#@ load("/helpers.star", "generate_kibana_tls")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("certificates.lib.yaml", "generate_dns_names", "generate_self_signed_issuer", "generate_ca_issuer", "generate_ca_certificate", "generate_certificate")

#@ if values.kibana.ingress.enabled:
#@ kibana_name = "kibana"
#@ kibana_namespace = values.kibana.namespace
#@ kibana_organization = "Kibana"
#@ kibana_self_signed_ca_issuer = kibana_name + "-self-signed-ca-issuer"
#@ kibana_ca = kibana_name + "-ca"
#@ kibana_ca_common_name = "Kibana CA"
#@ kibana_ca_dns_name = kibana_name + "ca"
#@ kibana_ca_key_pair = kibana_name + "-ca-key-pair"
#@ kibana_ca_issuer = kibana_name + "-ca-issuer"
#@ kibana_cert = kibana_name + "-cert"
#@ kibana_cert_duration = "87600h"
#@ kibana_cert_renew_before = "360h"

--- #@ generate_self_signed_issuer(kibana_self_signed_ca_issuer, kibana_namespace)
--- #@ generate_ca_certificate(kibana_ca, kibana_namespace, kibana_cert_duration, kibana_cert_renew_before, kibana_ca_key_pair, [kibana_organization], kibana_ca_common_name, [kibana_ca_dns_name], kibana_self_signed_ca_issuer)
--- #@ generate_ca_issuer(kibana_ca_issuer, kibana_namespace, kibana_ca_key_pair)

#@ kibana_tls_cert = "kibana-tls-cert"
#@ kibana_tls_secret = "kibana-tls"
#@ kibana_tls_common_name = "kibana"
#@ if generate_kibana_tls():
--- #@ generate_certificate(kibana_tls_cert, kibana_namespace, kibana_cert_duration, kibana_cert_renew_before, kibana_tls_secret, [kibana_organization], kibana_tls_common_name, [values.kibana.ingress.virtual_host_fqdn, "notary." + values.kibana.ingress.virtual_host_fqdn], kibana_ca_issuer)
#@ end

#@ if not generate_kibana_tls():
#@ ca_crt = getattr(values.kibana.ingress.tlsCertificate, "ca.crt")
#@ tls_crt = getattr(values.kibana.ingress.tlsCertificate, "tls.crt")
#@ tls_key = getattr(values.kibana.ingress.tlsCertificate, "tls.key")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ kibana_tls_secret
  namespace: #@ kibana_namespace
type: kubernetes.io/tls
data:
  #@ if/end ca_crt:
  ca.crt: #@ base64.encode(ca_crt)
  tls.crt: #@ base64.encode(tls_crt)
  tls.key: #@ base64.encode(tls_key)
#@ end

#@ end
